name: Export all icons to png

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: neomura/setup-aseprite-cli-action@v1.0.3
      - run: bash export_all.bash
        shell: bash
      - uses: actions/upload-artifact@v4
        with:
          name: icons
          path: out
